// Copies the OpenMoji drawings the Einkaufskorb uses into public/einkauf-icons/
// and writes src/lib/grocery-icons.ts (icon token → file). Run after changing
// icons in src/lib/groceries.ts:  node scripts/grocery-icons.mjs
// OpenMoji (openmoji.org) is CC BY-SA 4.0; the app credits it under the catalogue.
import fs from "node:fs";
import path from "node:path";

const root = path.dirname(path.dirname(new URL(import.meta.url).pathname));
const pkg = path.join(root, "node_modules/@iconify-json/openmoji");
const { icons, aliases = {}, width = 72, height = 72 } = JSON.parse(fs.readFileSync(path.join(pkg, "icons.json"), "utf8"));
const chars = JSON.parse(fs.readFileSync(path.join(pkg, "chars.json"), "utf8"));
const src = fs.readFileSync(path.join(root, "src/lib/groceries.ts"), "utf8");

// tokens: emoji or ":openmoji-name", from the catalogue ("=🍎") and the categories (icon: "🍎")
const tokens = new Set();
for (const line of src.split("\n").filter((l) => l.startsWith("add(")))
  for (const m of line.matchAll(/=([^,"/=]+?)(?=[,"])/g)) tokens.add(m[1].trim());
for (const m of src.matchAll(/icon: "([^"]+)"/g)) tokens.add(m[1]);

const resolve = (name) => icons[name] ?? (aliases[name] && icons[aliases[name].parent]);
const out = path.join(root, "public/einkauf-icons");
fs.rmSync(out, { recursive: true, force: true });
fs.mkdirSync(out, { recursive: true });
const map = {};
const missing = [];
for (const t of [...tokens].sort()) {
  let name;
  if (t.startsWith(":")) name = t.slice(1);
  else {
    const cps = [...t].map((c) => c.codePointAt(0).toString(16));
    name = chars[cps.join("-")] ?? chars[cps.filter((c) => c !== "fe0f").join("-")];
  }
  const icon = name && resolve(name);
  if (!icon) {
    missing.push(t);
    continue;
  }
  const w = icon.width ?? width, h = icon.height ?? height;
  fs.writeFileSync(path.join(out, `${name}.svg`), `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${w} ${h}">${icon.body}</svg>`);
  map[t] = name;
}
fs.writeFileSync(
  path.join(root, "src/lib/grocery-icons.ts"),
  `// Generated by scripts/grocery-icons.mjs, do not edit. Icon token → public/einkauf-icons/<file>.svg (OpenMoji, CC BY-SA 4.0).\nexport const ICON_FILES: Record<string, string> = ${JSON.stringify(map, null, 1)};\n`,
);
console.log(`${Object.keys(map).length} icons written` + (missing.length ? `, missing: ${missing.join(" ")}` : ""));
